/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apenastestando;

/**
 *
 * @author Jean
 */
public class Pesquisa extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pesquisa
     */
    public Pesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescr = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtRua2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNume = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBair = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCida = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        txtDia2 = new javax.swing.JTextField();
        txtMes1 = new javax.swing.JTextField();
        txtDia1 = new javax.swing.JTextField();
        txtAno1 = new javax.swing.JTextField();
        txtAno2 = new javax.swing.JTextField();
        txtMes2 = new javax.swing.JTextField();
        btnExcl = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnProcurar = new javax.swing.JButton();
        txtExc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);
        getContentPane().add(txtTitulo);
        txtTitulo.setBounds(130, 30, 190, 30);

        jLabel2.setText("Inicio do evento:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 70, 81, 30);

        jLabel4.setText("Titulo do evento:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 10, 82, 30);

        jLabel5.setText("Descrição do evento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 280, 102, 20);

        txaDescr.setColumns(20);
        txaDescr.setRows(5);
        jScrollPane1.setViewportView(txaDescr);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 300, 430, 80);

        jLabel6.setText("Local do evento:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 160, 80, 30);

        txtRua2.setEditable(false);
        getContentPane().add(txtRua2);
        txtRua2.setBounds(130, 190, 121, 30);

        jLabel7.setText("Rua:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 190, 23, 30);

        jLabel8.setText("Numero:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 190, 50, 30);

        txtNume.setEditable(false);
        getContentPane().add(txtNume);
        txtNume.setBounds(330, 190, 70, 30);

        jLabel9.setText("Bairro:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 190, 32, 30);

        txtBair.setEditable(false);
        getContentPane().add(txtBair);
        txtBair.setBounds(460, 190, 120, 30);

        jLabel10.setText("Cidade:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 230, 40, 30);

        txtCida.setEditable(false);
        getContentPane().add(txtCida);
        txtCida.setBounds(130, 230, 120, 30);

        jLabel11.setText("Estado:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(280, 230, 40, 30);

        jLabel12.setText("dia:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(120, 110, 30, 30);

        jLabel13.setText("mes:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 110, 30, 30);

        jLabel14.setText("ano:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(200, 110, 40, 30);

        jLabel15.setText("Fim do evento:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(360, 80, 72, 30);

        jLabel16.setText("dia:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(430, 110, 30, 30);

        jLabel17.setText("mes:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(330, 110, 30, 30);

        jLabel18.setText("ano:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(530, 110, 40, 30);

        txtEstado.setEditable(false);
        getContentPane().add(txtEstado);
        txtEstado.setBounds(330, 230, 70, 30);

        txtDia2.setEditable(false);
        getContentPane().add(txtDia2);
        txtDia2.setBounds(450, 110, 50, 30);

        txtMes1.setEditable(false);
        getContentPane().add(txtMes1);
        txtMes1.setBounds(50, 110, 50, 30);

        txtDia1.setEditable(false);
        getContentPane().add(txtDia1);
        txtDia1.setBounds(140, 110, 50, 30);

        txtAno1.setEditable(false);
        getContentPane().add(txtAno1);
        txtAno1.setBounds(230, 110, 70, 30);

        txtAno2.setEditable(false);
        getContentPane().add(txtAno2);
        txtAno2.setBounds(560, 110, 90, 30);

        txtMes2.setEditable(false);
        getContentPane().add(txtMes2);
        txtMes2.setBounds(360, 110, 50, 30);

        btnExcl.setText("Exluir evento");
        btnExcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExclActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcl);
        btnExcl.setBounds(180, 400, 140, 50);

        btnSalvar.setText("Salvar Mundanças");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(370, 400, 120, 50);

        btnProcurar.setText("PROCURAR");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcurar);
        btnProcurar.setBounds(370, 20, 110, 40);

        txtExc.setEditable(false);
        getContentPane().add(txtExc);
        txtExc.setBounds(500, 300, 170, 70);

        jLabel1.setText("Situação:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 280, 50, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        // TODO add your handling code here:
        ConexaoBanco conexao = new ConexaoBanco();
        conexao.abrirConecxao();
        String titu = txtTitulo.getText();
        String test = null;
        
        String mesin = "SELECT mesin FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        String diain = "SELECT diain FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        String anoin = "SELECT anoin FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        String mesfi = "SELECT mesfi FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        String diafi = "SELECT diafi FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        String anofi = "SELECT anofi FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        String durac = "SELECT durac FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        String rua = "SELECT rua FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        String numero = "SELECT numero FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        String bairro = "SELECT bairro FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        String cidade = "SELECT cidade FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        String estado = "SELECT estado FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        String descr = "SELECT descr FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        String excluido = "SELECT excluido FROM eventospub, eventosrasc WHERE titulo = '"+ titu+"';";
        
        txtMes1.setText(mesin);
        txtDia1.setText(diain);
        txtAno1.setText(anoin);
        txtMes2.setText(mesfi);
        txtDia2.setText(diafi);
        txtAno2.setText(anofi);
        txtRua2.setText(rua);
        txtNume.setText(numero);
        txtBair.setText(bairro);
        txtCida.setText(cidade);
        txtEstado.setText(estado);
        txaDescr.setText(descr);
        
        if(excluido.equals("true") || excluido.equals(0)){
            txtExc.setText("EXCLUIDO");
        }else{
            txtExc.setText("");
        }
        
        
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        ConexaoBanco conexao = new ConexaoBanco();
        conexao.abrirConecxao();
        String descr = txaDescr.getText();
        String titu = txtTitulo.getText();
        
        
        String query = "UPDATE eventospub SET descr = '"+ descr + "' WHERE titulo = '"+ titu+"';";
        String query2 = "UPDATE eventosrasc SET descr = '"+ descr + "' WHERE titulo = '"+ titu+"';";
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExclActionPerformed
        // TODO add your handling code here:
        ConexaoBanco conexao = new ConexaoBanco();
        conexao.abrirConecxao();
        String titu = txtTitulo.getText();
        
        String query = "UPDATE eventospub, eventosrasc SET excluido = '1' WHERE titulo = '"+ titu+"';";
        
    }//GEN-LAST:event_btnExclActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcl;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaDescr;
    private javax.swing.JTextField txtAno1;
    private javax.swing.JTextField txtAno2;
    private javax.swing.JTextField txtBair;
    private javax.swing.JTextField txtCida;
    private javax.swing.JTextField txtDia1;
    private javax.swing.JTextField txtDia2;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtExc;
    private javax.swing.JTextField txtMes1;
    private javax.swing.JTextField txtMes2;
    private javax.swing.JTextField txtNume;
    private javax.swing.JTextField txtRua2;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
