/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apenastestando;

import javax.swing.JOptionPane;

/**
 *
 * @author Jean
 */
public class Testando extends javax.swing.JFrame {

    /**
     * Creates new form Testando
     */
    public Testando() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanel = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txtTi = new javax.swing.JTextField();
        btnPub = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDes = new javax.swing.JTextArea();
        btnRasc = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBai = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbxEs = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbxdiain = new javax.swing.JComboBox<>();
        cbxmesin = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbxanoin = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbxdiafi = new javax.swing.JComboBox<>();
        cbxmesfi = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbxanofi = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel1.setText("Criador de Eventos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 20, 92, 20);
        getContentPane().add(txtTi);
        txtTi.setBounds(210, 130, 121, 30);

        btnPub.setText("Publicar evento");
        btnPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPubActionPerformed(evt);
            }
        });
        getContentPane().add(btnPub);
        btnPub.setBounds(240, 450, 107, 30);

        jLabel2.setText("Inicio do evento:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 81, 30);

        jLabel4.setText("Titulo do evento:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 130, 82, 30);

        jLabel5.setText("Descrição do evento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 330, 102, 20);

        txaDes.setColumns(20);
        txaDes.setRows(5);
        jScrollPane1.setViewportView(txaDes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 350, 310, 80);

        btnRasc.setText("Salvar Rascunho");
        btnRasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRascActionPerformed(evt);
            }
        });
        getContentPane().add(btnRasc);
        btnRasc.setBounds(80, 450, 113, 30);

        jLabel6.setText("Local do evento:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 170, 80, 30);
        getContentPane().add(txtRua);
        txtRua.setBounds(210, 170, 121, 30);

        jLabel7.setText("Rua:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 170, 23, 30);

        jLabel8.setText("Numero:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 170, 50, 30);
        getContentPane().add(txtNum);
        txtNum.setBounds(390, 170, 70, 30);

        jLabel9.setText("Bairro:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 210, 32, 30);
        getContentPane().add(txtBai);
        txtBai.setBounds(210, 210, 120, 30);

        jLabel10.setText("Cidade:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 250, 40, 30);
        getContentPane().add(txtCid);
        txtCid.setBounds(210, 250, 120, 30);

        jLabel11.setText("Estado:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(160, 290, 40, 30);

        cbxEs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PR", "RJ", "RN", "RO", "RS", "SE", "SP", "TO" }));
        getContentPane().add(cbxEs);
        cbxEs.setBounds(210, 290, 100, 30);

        jLabel12.setText("dia:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(100, 90, 30, 20);

        cbxdiain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbxdiain.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxdiainItemStateChanged(evt);
            }
        });
        getContentPane().add(cbxdiain);
        cbxdiain.setBounds(120, 90, 40, 30);

        cbxmesin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(cbxmesin);
        cbxmesin.setBounds(40, 90, 40, 30);

        jLabel13.setText("mes:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 90, 30, 20);

        jLabel14.setText("ano:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(170, 90, 40, 20);

        cbxanoin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        getContentPane().add(cbxanoin);
        cbxanoin.setBounds(200, 90, 80, 20);

        jLabel15.setText("Fim do evento:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(300, 50, 72, 30);

        jLabel16.setText("dia:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(390, 90, 30, 20);

        cbxdiafi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbxdiafi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxdiafiItemStateChanged(evt);
            }
        });
        getContentPane().add(cbxdiafi);
        cbxdiafi.setBounds(410, 90, 37, 20);

        cbxmesfi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(cbxmesfi);
        cbxmesfi.setBounds(330, 90, 37, 20);

        jLabel17.setText("mes:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(300, 90, 30, 20);

        jLabel18.setText("ano:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(460, 90, 40, 20);

        cbxanofi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        getContentPane().add(cbxanofi);
        cbxanofi.setBounds(490, 90, 50, 20);

        jButton2.setText("Pesquisar Evento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 450, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void limpa(){
        cbxmesin.setSelectedItem(0);
        cbxdiain.setSelectedItem(0);
        cbxanoin.setSelectedItem(0);
        cbxmesfi.setSelectedItem(0);
        cbxdiafi.setSelectedItem(0);
        cbxanofi.setSelectedItem(0);
        txtTi.setText("");
        txtRua.setText("");
        txtNum.setText("");
        txtBai.setText("");
        txtCid.setText("");
        cbxEs.setSelectedItem(0);
        txaDes.setText("");
    }
    
    private void btnPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPubActionPerformed
        ConexaoBanco conexao = new ConexaoBanco();
        conexao.abrirConecxao();
        
        int mesin;
        mesin = Integer.parseInt((String) cbxmesin.getSelectedItem());
        int diain;
        diain = Integer.parseInt((String) cbxdiain.getSelectedItem());
        int anoin;
        anoin = Integer.parseInt((String) cbxanoin.getSelectedItem());
        int mesfi = Integer.parseInt((String) cbxmesfi.getSelectedItem());
        int diafi = Integer.parseInt((String) cbxdiafi.getSelectedItem());
        int anofi = Integer.parseInt((String) cbxanofi.getSelectedItem());
        String titulo = txtTi.getText();
        String rua = txtRua.getText();
        String numero = txtNum.getText();
        String bairro = txtBai.getText();
        String cidade = txtCid.getText();
        String estado = (cbxEs.getSelectedItem().toString());
        String desc = txaDes.getText();
        
        if(mesin==0 || diain==0 || anoin==0 || mesfi==0 || diafi==0||anofi==0 || titulo.equals("")|| rua.equals("")
           || numero.equals("") || bairro.equals("") || cidade.equals("")||estado.equals("")|| desc.equals("")){
            
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para publicar o evento");
            
        } else {
            int durac = (anofi - anoin)*365 + (mesfi - mesin)*30 + (diafi - diain);
            
            String query = "INSERT INTO eventospub (diain, mesin, anoin, diate, meste, anote, titulo, rua, numero, bairro, cidade, estado, descr)"
                + " VALUES ('" + diain + "', '"+ mesin + "', '" + anoin + "', '"+ diafi + "', '" + mesfi + "', '" + anofi + "', '"+ durac + "', '"
                + titulo + "', '"+ rua + "', '"+ numero +"', '"+ bairro + "', '"+ cidade + "', '" + estado + "', '"+ desc + "');";
            limpa();
        }
        
    }//GEN-LAST:event_btnPubActionPerformed
        
    private void cbxdiainItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxdiainItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxdiainItemStateChanged

    private void cbxdiafiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxdiafiItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxdiafiItemStateChanged

    private void btnRascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRascActionPerformed
        ConexaoBanco conexao = new ConexaoBanco();
        conexao.abrirConecxao();
        
        int mesin = (int) cbxmesin.getSelectedItem();
        int diain = (int) cbxdiain.getSelectedItem();
        int anoin = (int) cbxanoin.getSelectedItem();
        int mesfi = (int) cbxmesfi.getSelectedItem();
        int diafi = (int) cbxdiafi.getSelectedItem();
        int anofi = (int) cbxanofi.getSelectedItem();
        String titulo = txtTi.getText();
        String rua = txtRua.getText();
        String numero = txtNum.getText();
        String bairro = txtBai.getText();
        String cidade = txtCid.getText();
        String estado = (cbxEs.getSelectedItem().toString());
        String desc = txaDes.getText();
        
        int durac = (anofi - anoin)*365 + (mesfi - mesin)*30 + (diafi - diain);
            
        String query = "INSERT INTO eventosrasc (diain, mesin, anoin, diate, meste, anote, titulo, rua, numero, bairro, cidade, estado, descr)"
                + " VALUES ('" + diain + "', '"+ mesin + "', '" + anoin + "', '"+ diafi + "', '" + mesfi + "', '" + anofi + "', '"+ durac + "', '"
                + titulo + "', '"+ rua + "', '"+ bairro + "', '"+ cidade + "', '" + "', '" + estado + "', '"+ desc + "');";
        
        limpa();
    }//GEN-LAST:event_btnRascActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Pesquisa pesquisar = new Pesquisa();
        jDesktopPanel.add(pesquisar);
        pesquisar.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Testando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Testando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Testando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Testando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Testando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPub;
    private javax.swing.JButton btnRasc;
    private javax.swing.JComboBox<String> cbxEs;
    private javax.swing.JComboBox<String> cbxanofi;
    private javax.swing.JComboBox<String> cbxanoin;
    private javax.swing.JComboBox<String> cbxdiafi;
    private javax.swing.JComboBox<String> cbxdiain;
    private javax.swing.JComboBox<String> cbxmesfi;
    private javax.swing.JComboBox<String> cbxmesin;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaDes;
    private javax.swing.JTextField txtBai;
    private javax.swing.JTextField txtCid;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTi;
    // End of variables declaration//GEN-END:variables
}
